- id: redeploy-contestsuite
  execute-command: "/var/scripts/redeploy_contestsuite.sh"
  command-working-directory: "/var/contestsuite"
  trigger-rule:
    and:
    - match:
        type: payload-hmac-sha1
        secret: mysecret
        parameter:
          source: header
          name: X-Hub-Signature
    - match:
        type: value
        value: "FSU-ACM/Programming-Contest-Suite"
        parameter:
          source: payload
          name: repository
    - match:
        type: value
        value: "Publish Docker image"
        parameter:
          source: payload
          name: workflow
