# This is a basic workflow to help you get started with Actions
name: Webhook Test

on:
  watch:
    types: [started]
jobs:
    redeploy:
      name: Test webhook call
      runs-on: ubuntu-latest
      steps:
        - name: Invoke test hook
          uses: distributhor/workflow-webhook@v2
          env:
            webhook_url: ${{ secrets.TEST_WEBHOOK_URL }}
            webhook_secret: ${{ secrets.TEST_WEBHOOK_SECRET }}
